[workspace]
resolver = "2"
members = [
    "day00",
    "old01",
    "old02",
    "old03",
    "old04",
    "old05",
    "old06",
    "day2401",
    "day2402",
    "day2403",
    "day2404",
    "day2405",
    "lib", "day2406", "day2407",
]
